"""Add safe parsing metadata to jobs

Revision ID: c7bbc63c49c7
Revises: e50ad960f737
Create Date: 2026-04-30 11:37:51.467283
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7bbc63c49c7'
down_revision: str | None = 'e50ad960f737'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('raw_jd_text', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('parsing_source', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('parsing_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'parsing_status')
    op.drop_column('jobs', 'parsing_source')
    op.drop_column('jobs', 'raw_jd_text')
    # ### end Alembic commands ###

